/// UI strings for the farmer-facing screens.
/// Add new keys here rather than placing user-visible text directly in widgets.
abstract final class AppStrings {
  static String language = 'English';

  static const _hindi = <String, String>{
    'smart companion': 'आपका स्मार्ट खेती साथी',
    'namaste farmer': 'नमस्ते किसान! 👋',
    'hero message': 'स्वस्थ फसलें। बेहतर फैसले। बेहतर पैदावार।',
    'currently growing': 'वर्तमान फसल',
    'detect disease': 'फसल रोग पहचानें',
    'detect disease sub': 'फोटो लें और फसल की समस्या पहचानें',
    'farming advice': 'खेती की सलाह लें',
    'farming advice sub': 'CropMitra AI से अपनी फसल के बारे में पूछें',
    'community pulse': 'कम्युनिटी क्रॉप पल्स',
    'community pulse sub':
        'रोग रिपोर्ट करें • हॉटस्पॉट देखें • फॉलो-अप ट्रैक करें',
    'quick access': 'त्वरित विकल्प',
    'weather': 'मौसम',
    'tools': 'उपकरण',
    'ai assistant': 'AI सहायक',
    'farming tip': 'आज की खेती सलाह',
    'tip body':
        'वाष्पीकरण कम करने और जड़ों को स्वस्थ रखने के लिए सुबह जल्दी सिंचाई करें।',
    'home': 'होम',
    'disease': 'रोग',
    'chat': 'चैट',
    'report crop problem': 'फसल समस्या रिपोर्ट करें',
    'hotspot map': 'रोग हॉटस्पॉट मानचित्र',
    'officer dashboard': 'अधिकारी डैशबोर्ड',
    'treatment follow up': 'उपचार फॉलो-अप',
    'farming tools': 'खेती उपकरण',
    'weather forecast': 'मौसम और पूर्वानुमान',
    'enter city': 'शहर का नाम लिखें...',
    'ask crops': 'अपनी फसल के बारे में पूछें...',
    'choose language': 'अपनी भाषा चुनें',
    'language hint': 'AI सलाह और ऐप की स्क्रीन आपकी चुनी हुई भाषा में दिखेगी।',
    'report disease': 'फसल समस्या रिपोर्ट करें',
    'map subtitle': 'क्षेत्र के अनुसार सामुदायिक जोखिम देखें',
    'dashboard subtitle': 'कृषि अधिकारियों के लिए निगरानी दृश्य',
    'follow subtitle': 'दिन 1, 7 और 14 की तस्वीरों की तुलना करें',
  };

  static String t(String key) {
    return _translations[language]?[key] ?? key;
  }

  static final _translations = <String, Map<String, String>>{
    'Hindi': _hindi,
    'Marathi': {
      'smart companion': 'तुमचा स्मार्ट शेती साथी',
      'namaste farmer': 'नमस्कार शेतकरी! 👋',
      'hero message': 'निरोगी पिके. चांगले निर्णय. मोठे उत्पादन.',
      'currently growing': 'सध्या पीक',
      'detect disease': 'पीक रोग ओळखा',
      'detect disease sub': 'फोटो घ्या आणि पिकाची समस्या ओळखा',
      'farming advice': 'शेतीचा सल्ला घ्या',
      'farming advice sub': 'CropMitra AI ला तुमच्या पिकाबद्दल विचारा',
      'community pulse': 'समुदाय पीक पल्स',
      'community pulse sub': 'रोग नोंदवा • हॉटस्पॉट पाहा • फॉलो-अप ट्रॅक करा',
      'quick access': 'जलद पर्याय',
      'weather': 'हवामान',
      'tools': 'साधने',
      'ai assistant': 'AI सहाय्यक',
      'farming tip': 'आजचा शेती सल्ला',
      'tip body': 'बाष्पीभवन कमी करण्यासाठी सकाळी लवकर पाणी द्या.',
      'home': 'मुख्यपृष्ठ',
      'disease': 'रोग',
      'chat': 'चॅट',
      'choose language': 'तुमची भाषा निवडा',
      'language hint': 'AI सल्ला आणि ॲप स्क्रीन निवडलेल्या भाषेत दिसेल.',
    },
    'Punjabi': {
      'smart companion': 'ਤੁਹਾਡਾ ਸਮਾਰਟ ਖੇਤੀ ਸਾਥੀ',
      'namaste farmer': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਕਿਸਾਨ! 👋',
      'hero message': 'ਸਿਹਤਮੰਦ ਫਸਲਾਂ। ਬਿਹਤਰ ਫੈਸਲੇ। ਵੱਡੀ ਪੈਦਾਵਾਰ।',
      'currently growing': 'ਮੌਜੂਦਾ ਫਸਲ',
      'detect disease': 'ਫਸਲ ਰੋਗ ਪਛਾਣੋ',
      'detect disease sub': 'ਫੋਟੋ ਲਓ ਅਤੇ ਫਸਲ ਦੀ ਸਮੱਸਿਆ ਪਛਾਣੋ',
      'farming advice': 'ਖੇਤੀ ਸਲਾਹ ਲਵੋ',
      'farming advice sub': 'ਆਪਣੀ ਫਸਲ ਬਾਰੇ CropMitra AI ਨੂੰ ਪੁੱਛੋ',
      'community pulse': 'ਕਮਿਊਨਿਟੀ ਕਰੌਪ ਪਲਸ',
      'community pulse sub':
          'ਰੋਗ ਰਿਪੋਰਟ ਕਰੋ • ਹੌਟਸਪੌਟ ਵੇਖੋ • ਫਾਲੋ-ਅੱਪ ਟਰੈਕ ਕਰੋ',
      'quick access': 'ਤੁਰੰਤ ਵਿਕਲਪ',
      'weather': 'ਮੌਸਮ',
      'tools': 'ਸਾਧਨ',
      'ai assistant': 'AI ਸਹਾਇਕ',
      'farming tip': 'ਅੱਜ ਦੀ ਖੇਤੀ ਸਲਾਹ',
      'tip body': 'ਬਾਫ਼ ਘਟਾਉਣ ਲਈ ਸਵੇਰੇ ਜਲਦੀ ਸਿੰਚਾਈ ਕਰੋ।',
      'home': 'ਹੋਮ',
      'disease': 'ਰੋਗ',
      'chat': 'ਚੈਟ',
      'choose language': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
      'language hint': 'AI ਸਲਾਹ ਅਤੇ ਐਪ ਸਕ੍ਰੀਨਾਂ ਚੁਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦਿਖਣਗੀਆਂ।',
    },
    'Bengali': {
      'smart companion': 'আপনার স্মার্ট কৃষি সঙ্গী',
      'namaste farmer': 'নমস্কার কৃষক! 👋',
      'hero message': 'সুস্থ ফসল। ভালো সিদ্ধান্ত। বড় ফলন।',
      'currently growing': 'বর্তমান ফসল',
      'detect disease': 'ফসলের রোগ শনাক্ত করুন',
      'detect disease sub': 'ছবি তুলুন এবং ফসলের সমস্যা শনাক্ত করুন',
      'farming advice': 'কৃষি পরামর্শ নিন',
      'farming advice sub': 'CropMitra AI-কে আপনার ফসল সম্পর্কে জিজ্ঞাসা করুন',
      'community pulse': 'কমিউনিটি ক্রপ পালস',
      'community pulse sub':
          'রোগ রিপোর্ট করুন • হটস্পট দেখুন • ফলো-আপ ট্র্যাক করুন',
      'quick access': 'দ্রুত বিকল্প',
      'weather': 'আবহাওয়া',
      'tools': 'সরঞ্জাম',
      'ai assistant': 'AI সহায়ক',
      'farming tip': 'আজকের কৃষি পরামর্শ',
      'tip body': 'বাষ্পীভবন কমাতে ভোরে সেচ দিন।',
      'home': 'হোম',
      'disease': 'রোগ',
      'chat': 'চ্যাট',
      'choose language': 'আপনার ভাষা বেছে নিন',
      'language hint': 'AI পরামর্শ ও অ্যাপ স্ক্রিন আপনার ভাষায় দেখাবে।',
    },
    'Gujarati': {
      'smart companion': 'તમારો સ્માર્ટ ખેતી સાથી',
      'namaste farmer': 'નમસ્તે ખેડૂત! 👋',
      'hero message': 'તંદુરસ્ત પાક. સારા નિર્ણયો. વધુ ઉત્પાદન.',
      'currently growing': 'હાલનો પાક',
      'detect disease': 'પાકનો રોગ શોધો',
      'detect disease sub': 'ફોટો લો અને પાકની સમસ્યા ઓળખો',
      'farming advice': 'ખેતીની સલાહ મેળવો',
      'farming advice sub': 'તમારા પાક વિશે CropMitra AI ને પૂછો',
      'community pulse': 'કમ્યુનિટી ક્રોપ પલ્સ',
      'community pulse sub': 'રોગ નોંધાવો • હોટસ્પોટ જુઓ • ફોલો-અપ ટ્રેક કરો',
      'quick access': 'ઝડપી વિકલ્પો',
      'weather': 'હવામાન',
      'tools': 'સાધનો',
      'ai assistant': 'AI સહાયક',
      'farming tip': 'આજની ખેતી સલાહ',
      'tip body': 'બાષ્પીભવન ઘટાડવા વહેલી સવારે સિંચાઈ કરો.',
      'home': 'હોમ',
      'disease': 'રોગ',
      'chat': 'ચેટ',
      'choose language': 'તમારી ભાષા પસંદ કરો',
      'language hint': 'AI સલાહ અને એપ સ્ક્રીન પસંદ કરેલી ભાષામાં દેખાશે.',
    },
    'Tamil': {
      'smart companion': 'உங்கள் ஸ்மார்ட் விவசாய துணை',
      'namaste farmer': 'வணக்கம் விவசாயி! 👋',
      'hero message': 'ஆரோக்கியமான பயிர்கள். சிறந்த முடிவுகள். அதிக மகசூல்.',
      'currently growing': 'தற்போதைய பயிர்',
      'detect disease': 'பயிர் நோயை கண்டறியுங்கள்',
      'detect disease sub': 'புகைப்படம் எடுத்து பயிர் பிரச்சனையை அறியுங்கள்',
      'farming advice': 'விவசாய ஆலோசனை பெறுங்கள்',
      'farming advice sub':
          'உங்கள் பயிர்களைப் பற்றி CropMitra AI-யிடம் கேளுங்கள்',
      'community pulse': 'சமூக பயிர் பல்ஸ்',
      'community pulse sub':
          'நோயை பதிவு செய்யுங்கள் • ஹாட்ஸ்பாட் பாருங்கள் • பின்தொடருங்கள்',
      'quick access': 'விரைவு அணுகல்',
      'weather': 'வானிலை',
      'tools': 'கருவிகள்',
      'ai assistant': 'AI உதவியாளர்',
      'farming tip': 'இன்றைய விவசாய குறிப்பு',
      'tip body': 'ஆவியாதலை குறைக்க அதிகாலையில் நீர்ப்பாசனம் செய்யுங்கள்.',
      'home': 'முகப்பு',
      'disease': 'நோய்',
      'chat': 'அரட்டை',
      'choose language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'language hint':
          'AI ஆலோசனையும் செயலி திரைகளும் தேர்ந்த மொழியில் காட்டப்படும்.',
    },
    'Telugu': {
      'smart companion': 'మీ స్మార్ట్ వ్యవసాయ సహచరుడు',
      'namaste farmer': 'నమస్కారం రైతు! 👋',
      'hero message': 'ఆరోగ్యకరమైన పంటలు. మెరుగైన నిర్ణయాలు. అధిక దిగుబడి.',
      'currently growing': 'ప్రస్తుత పంట',
      'detect disease': 'పంట వ్యాధిని గుర్తించండి',
      'detect disease sub': 'ఫోటో తీసి పంట సమస్యను గుర్తించండి',
      'farming advice': 'వ్యవసాయ సలహా పొందండి',
      'farming advice sub': 'మీ పంట గురించి CropMitra AIని అడగండి',
      'community pulse': 'కమ్యూనిటీ క్రాప్ పల్స్',
      'community pulse sub':
          'వ్యాధి నివేదించండి • హాట్‌స్పాట్ చూడండి • ఫాలో-అప్ ట్రాక్ చేయండి',
      'quick access': 'త్వరిత ఎంపికలు',
      'weather': 'వాతావరణం',
      'tools': 'పరికరాలు',
      'ai assistant': 'AI సహాయకుడు',
      'farming tip': 'నేటి వ్యవసాయ సలహా',
      'tip body': 'ఆవిరి తగ్గించడానికి ఉదయాన్నే నీరు పెట్టండి.',
      'home': 'హోమ్',
      'disease': 'వ్యాధి',
      'chat': 'చాట్',
      'choose language': 'మీ భాషను ఎంచుకోండి',
      'language hint':
          'AI సలహా మరియు యాప్ స్క్రీన్లు ఎంచుకున్న భాషలో కనిపిస్తాయి.',
    },
    'Kannada': {
      'smart companion': 'ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಂಗಾತಿ',
      'namaste farmer': 'ನಮಸ್ಕಾರ ರೈತರೇ! 👋',
      'hero message': 'ಆರೋಗ್ಯಕರ ಬೆಳೆಗಳು. ಉತ್ತಮ ನಿರ್ಧಾರಗಳು. ಹೆಚ್ಚಿನ ಇಳುವರಿ.',
      'currently growing': 'ಪ್ರಸ್ತುತ ಬೆಳೆ',
      'detect disease': 'ಬೆಳೆ ರೋಗ ಪತ್ತೆ ಮಾಡಿ',
      'detect disease sub': 'ಫೋಟೋ ತೆಗೆದು ಬೆಳೆ ಸಮಸ್ಯೆ ಗುರುತಿಸಿ',
      'farming advice': 'ಕೃಷಿ ಸಲಹೆ ಪಡೆಯಿರಿ',
      'farming advice sub': 'ನಿಮ್ಮ ಬೆಳೆಯ ಬಗ್ಗೆ CropMitra AIಯನ್ನು ಕೇಳಿ',
      'community pulse': 'ಸಮುದಾಯ ಬೆಳೆ ಪಲ್ಸ್',
      'community pulse sub':
          'ರೋಗ ವರದಿ ಮಾಡಿ • ಹಾಟ್‌ಸ್ಪಾಟ್ ನೋಡಿ • ಫಾಲೋ-ಅಪ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'quick access': 'ತ್ವರಿತ ಆಯ್ಕೆಗಳು',
      'weather': 'ಹವಾಮಾನ',
      'tools': 'ಉಪಕರಣಗಳು',
      'ai assistant': 'AI ಸಹಾಯಕ',
      'farming tip': 'ಇಂದಿನ ಕೃಷಿ ಸಲಹೆ',
      'tip body': 'ಆವಿಯಾಗುವಿಕೆ ಕಡಿಮೆ ಮಾಡಲು ಬೆಳಿಗ್ಗೆ ಬೇಗ ನೀರಾವರಿ ಮಾಡಿ.',
      'home': 'ಮುಖಪುಟ',
      'disease': 'ರೋಗ',
      'chat': 'ಚಾಟ್',
      'choose language': 'ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'language hint':
          'AI ಸಲಹೆ ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ಪರದೆಗಳು ಆಯ್ದ ಭಾಷೆಯಲ್ಲಿ ಕಾಣುತ್ತವೆ.',
    },
    'Malayalam': {
      'smart companion': 'നിങ്ങളുടെ സ്മാർട്ട് കൃഷി കൂട്ടുകാരൻ',
      'namaste farmer': 'നമസ്കാരം കർഷകാ! 👋',
      'hero message': 'ആരോഗ്യകരമായ വിളകൾ. മികച്ച തീരുമാനങ്ങൾ. കൂടുതൽ വിളവ്.',
      'currently growing': 'നിലവിലെ വിള',
      'detect disease': 'വിള രോഗം കണ്ടെത്തുക',
      'detect disease sub': 'ഫോട്ടോ എടുത്ത് വിള പ്രശ്നം തിരിച്ചറിയുക',
      'farming advice': 'കൃഷി ഉപദേശം നേടുക',
      'farming advice sub':
          'നിങ്ങളുടെ വിളയെക്കുറിച്ച് CropMitra AIയോട് ചോദിക്കുക',
      'community pulse': 'കമ്മ്യൂണിറ്റി ക്രോപ്പ് പൾസ്',
      'community pulse sub':
          'രോഗം റിപ്പോർട്ട് ചെയ്യുക • ഹോട്ട്സ്പോട്ട് കാണുക • ഫോളോ-അപ്പ് ട്രാക്ക് ചെയ്യുക',
      'quick access': 'ദ്രുത പ്രവേശനം',
      'weather': 'കാലാവസ്ഥ',
      'tools': 'ഉപകരണങ്ങൾ',
      'ai assistant': 'AI സഹായി',
      'farming tip': 'ഇന്നത്തെ കൃഷി നിർദേശം',
      'tip body': 'ബാഷ്പീകരണം കുറയ്ക്കാൻ രാവിലെ നേരത്തെ നനയ്ക്കുക.',
      'home': 'ഹോം',
      'disease': 'രോഗം',
      'chat': 'ചാറ്റ്',
      'choose language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'language hint':
          'AI ഉപദേശവും ആപ്പ് സ്ക്രീനുകളും തിരഞ്ഞെടുത്ത ഭാഷയിൽ കാണിക്കും.',
    },
  };
}
